apiVersion: v1
kind: ConfigMap
metadata:
  name: retina-config
  namespace: monitoring
data:
  config.yaml: |-
    apiServer:
      host: 0.0.0.0
      port: 10093
    logLevel: info
    enabledPlugin: ["dropreason","packetforward","linuxutil","dns","packetparser"]
    metricsInterval: 10
    enableTelemetry: false
    enablePodLevel: true
    remoteContext: true
    enableAnnotations: true

