apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: opensearch
data:
  opensearch.yml: |
    network.host: 0.0.0.0
    discovery.type: single-node
    plugins.security.disabled: true

