apiVersion: v1
kind: ConfigMap
metadata:
  name: otelmetrics
  namespace: monitoring
  labels:
    app: otelmetrics
data:
  config.yaml: |
    receivers:
      kubeletstats:
        collection_interval: 10s
        auth_type: "serviceAccount"
        endpoint: "https://${env:K8S_NODE_NAME}:10250"
        insecure_skip_verify: true
    exporters:
      otlp/metrics:
        endpoint: data-prepper.monitoring.svc:21891
        tls:
          insecure: true
    service:
      pipelines:
        metrics:
          receivers: [kubeletstats]
          exporters: [otlp/metrics]

