apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otelmetrics
  namespace: monitoring
  labels:
    app: otelmetrics
spec:
  selector:
    matchLabels:
      app: otelmetrics
  template:
    metadata:
      labels:
        app: otelmetrics
    spec:
      serviceAccountName: otelmetrics
      containers:
      - name: otelmetrics
        image: otel/opentelemetry-collector-contrib
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args: ["--config", "/etc/config/config.yaml", "--feature-gates=receiver.kubeletstats.enableCPUUsageMetrics"]
        volumeMounts:
        - name: config
          mountPath: /etc/config
        imagePullPolicy: IfNotPresent
      volumes:
        - name: config
          configMap:
            name: otelmetrics

