apiVersion: v1
kind: ConfigMap
metadata:
  name: oteltraces
  namespace: monitoring
  labels:
    app: oteltraces
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch/traces:
        timeout: 1s
        send_batch_size: 50
    exporters:
      otlp/data-prepper:
        endpoint: data-prepper.monitoring.svc:21890
        tls:
          insecure: true
    service:
      pipelines:
       traces:
          receivers: [otlp]
          processors: [batch/traces]
          exporters: [otlp/data-prepper]

