apiVersion: v1
kind: ConfigMap
metadata:
  name: oteltraces
  namespace: monitoring
  labels:
    app: oteltraces
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_compact:
            endpoint: 0.0.0.0:6831
          thrift_http:
            endpoint: 0.0.0.0:14628
    processors:
      batch/traces:
        timeout: 1s
        send_batch_size: 50
    exporters:
      otlp/data-prepper:
        endpoint: data-prepper.monitoring.svc:21890
        tls:
          insecure: true
      otlp/jaeger:
        endpoint: jaeger.monitoring.svc:4317
        tls:
          insecure: true
    service:
      pipelines:
       traces:
          receivers: [otlp, jaeger]
          processors: [batch/traces]
          exporters: [otlp/data-prepper, otlp/jaeger]

