apiVersion: v1
kind: ConfigMap
metadata:
  name: otelevents
  namespace: monitoring
  labels:
    app: otelevents
data:
  config.yaml: |
    receivers:
      k8s_events:
    exporters:
      otlp/logs:
        endpoint: data-prepper.monitoring.svc:21892
        tls:
          insecure: true
    service:
      pipelines:
        logs:
          receivers: [k8s_events]
          exporters: [otlp/logs]

