apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: elasticsearch-config
  labels:
    app: elasticsearch
    role: master
data:
  elasticsearch.yml: |-
    network.host: 0.0.0.0
    xpack.security.enabled: false
    xpack.security.autoconfiguration.enabled: false
    xpack.security.dls_fls.enabled: false

