defaultSettings:
  allowCollectingLonghornUsageMetrics: true
  deletingConfirmationFlag: true
  backupTarget: "nfs://longhorn-nfs-svc.longhorn-system.svc:/opt/backupstore"
  concurrentAutomaticEngineUpgradePerNodeLimit: 1
metrics:
  serviceMonitor:
    enabled: true
persistence:
  defaultClassReplicaCount: 2

