apiVersion: v1
kind: Secret
metadata:
  name: chartmuseum
  namespace: chartmuseum
  labels:
    app.kubernetes.io/name: chartmuseum
    app.kubernetes.io/instance: chartmuseum
type: Opaque
data:
  BASIC_AUTH_PASS: cGFzc3dvcmQ=
  BASIC_AUTH_USER: YWRtaW4=

