ingressNginx:
  enabled: true
kubeApiServer:
  enabled: false
kubelet:
  serviceMonitor:
    cAdvisor: false
prometheus:
  prometheusSpec:
    retention: 1d
rkeControllerManager:
  enabled: true
rkeEtcd:
  enabled: true
rkeProxy:
  enabled: true
rkeScheduler:
  enabled: true

