nodeExporter:
  enabled: true
prometheus:
  prometheusSpec:
    retention: 1d
rke2ControllerManager:
  enabled: true
rke2Etcd:
  enabled: true
rke2IngressNginx:
  enabled: true
rke2Proxy:
  enabled: true
rke2Scheduler:
  enabled: true

