alertmanager:
  config:
    receivers:
      - name: slack-receiver
        slack_configs:
          - send_resolved: true
            api_url: >-
              https://hooks.slack.com/services/xxxxxxxxx/xxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxx
            channel: '#ec2-cluster-1'
      - name: 'null'
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: 'slack-receiver'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'
        continue: true
      - match: {}
        match_re:
          alertname: '.*'
        receiver: slack-receiver
grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - grafanacgn.ddns.net
ingressNginx:
  enabled: true
kubeApiServer:
  enabled: false
prometheus:
  prometheusSpec:
    remoteWrite:
    - url: https://prometheus-us-central1.grafana.net/api/prom/push
      basicAuth:
        username: 
          name: remote-writer
          key: username
        password: 
          name: remote-writer
          key: password
    replicaExternalLabelName: "__replica__"
    externalLabels: {cluster: "${cluster_name}"}
    retention: 1d
    scrapeInterval: 1m
  serviceMonitor:
    selfMonitor: false

