apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf
  namespace: monitoring
  labels:
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: telegraf
data:
  telegraf.conf: |+
    
    [agent]
      collection_jitter = "0s"
      debug = false
      flush_interval = "10s"
      flush_jitter = "0s"
      hostname = "$HOSTNAME"
      interval = "10s"
      logfile = ""
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      omit_hostname = false
      precision = ""
      quiet = false
      round_interval = true

    [[outputs.influxdb_v2]]
      urls = [ "http://influxdb.monitoring.svc:8086" ]
      token ="pre-shared-local-token"
      organization = "aks-cluster"
      bucket = "metrics"

    [[inputs.kube_inventory]]
      url = "https://kubernetes.default.svc"
      namespace = ""
      bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
      insecure_skip_verify = true

