apiVersion: v1
kind: Namespace
metadata:
  name: retina-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: retina-agent
  namespace: retina-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: retina-cluster-reader
  namespace: retina-system
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "services", "replicationcontrollers", "nodes", "namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["networking.azure.com"]
    resources: ["clusterobservers"]
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - retina.sh
    resources:
      - retinaendpoints
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: retina-cluster-reader-binding
  namespace: retina-system
subjects:
  - kind: ServiceAccount
    name: retina-agent
    namespace: retina-system
roleRef:
  kind: ClusterRole
  name: retina-cluster-reader
  apiGroup: rbac.authorization.k8s.io

