apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rancher-monitoring-prometheus
  namespace: cattle-monitoring-system
  labels:
    name: rancher-monitoring-prometheus
spec:
  selector:
    matchLabels:
      app: rancher-monitoring-prometheus
  namespaceSelector:
    matchNames:
    - cattle-monitoring-system
  endpoints:
  - port: http-web

