{
 "title": "Kubernetes / Retina / Pod Traffic",
 "tags": [ "k8s:network-observability" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod Name ",
    "query": {
     "query": "query_result(networkobservability_adv_forward_count)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Outgoing Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(networkobservability_adv_forward_count{direction=\"EGRESS\"}[4m]))",
     "legendFormat": "Total PPS"
    }
   ]
  },
  {
   "title": "Incoming Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(networkobservability_adv_forward_count{direction=\"INGRESS\"}[4m0s]))",
     "legendFormat": "Total PPS"
    }
   ]
  },
  {
   "title": "All Outgoing pps per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(source_podname) (irate(networkobservability_adv_forward_count{direction=\"EGRESS\", destination_podname!=\"unknown\", source_podname!=\"unknown\"}[4m0s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Incoming pps per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(destination_podname) (irate(networkobservability_adv_forward_count{direction=\"INGRESS\", destination_podname!=\"unknown\", source_podname!=\"unknown\"}[4m0s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Pods Outgoing traffic",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(10, sum by(source_podname) (irate(networkobservability_adv_forward_count{direction=\"EGRESS\", source_podname!=\"unknown\"}[4m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Pods Incoming traffic",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "topk(10, sum by(destination_podname) (irate(networkobservability_adv_forward_count{direction=\"INGRESS\",destination_podname!=\"unknown\"}[4m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}