alertmanager:
  config:
    receivers:
      - name: slack-receiver
        slack_configs:
          - send_resolved: true
            api_url: >-
              https://hooks.slack.com/services/xxxxxxxxxxxxx/xxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxx
            channel: '#gcp-cluster'
      - name: 'null'
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: 'slack-receiver'
      routes:
      - match:
          alertname: etcdHighNumberOfFailedGRPCRequests
        receiver: 'null'
      - match:
          alertname: Watchdog
        receiver: 'null'
        continue: true
      - match: {}
        match_re:
          alertname: '.*'
        receiver: slack-receiver
grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - grafanacgn.ddns.net
ingressNginx:
  enabled: true
kubelet:
  serviceMonitor:
    cAdvisor: false
prometheus:
  prometheusSpec:
    retention: 1d
rkeControllerManager:
  enabled: true
rkeEtcd:
  enabled: true
rkeProxy:
  enabled: true
rkeScheduler:
  enabled: true

